[wokwi]
version = 1
# Exercise
# firmware = "target/riscv32imc-unknown-none-elf/release/dma"
# elf = "target/riscv32imc-unknown-none-elf/release/dma"

# Solution
firmware = 'target/riscv32imc-unknown-none-elf/release/examples/dma'
elf = 'target/riscv32imc-unknown-none-elf/release/examples/dma'
